### PR TITLE
Updated to api: 3.9.0

### PR DESCRIPTION
**Pull request by iZeaoGamer**
This update includes fixes for Pocketmine API 3.9.0
Please merge ASAP. Thank you!

### CODE REVIEW

**Comment by SOF3** [comment]
EconomySell is unmaintained.

**Comment by TDMidkwhatisxd** [comment]
RIP economysell :)

**Comment by SOF3** [comment]
Packet use should have used the mcpe-protocol attribute in plugin.yml anyway. Merging this leads to falsely declared compatibility with older client versions.
Please declare the compatible protocol versions in plugin.yml.

**Comment by iZeaoGamer** [comment]
Done. Would you like me to add support for API 3.9.0 only in plugin.yml, or keep it to 3.0.0?

**Comment by SOF3** [comment]
@iZeaoGamer protocol changes are independent of API version.

**Comment by EduGH7** [comment]
Hey, guys! Could you do a fix for EconomyShop please? It have the same protocol issue but I try to change the ItemDisplay.php and when I enter to the server it appears a server internal error and in the console there is some error of unespecified AddItemActorPacket

**Comment by iZeaoGamer** [comment]
A fix should be on another Pull request - Silly me; I forgot to add those changes as well - Awaiting for their approval.

**Pull request merged**
